<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Login"
           tests="5"
           failures="1"
           errors="0"
           skipped="0"
           time="7.865">
  <properties />
            <testcase name="verifyLoginWithValidCredentials" time="4.870" classname="com.orangehrm.tests.LoginTest">
                <failure type="java.lang.AssertionError"
                  message="Verify Welcome Message expected [Welcome Vishnu] but found [Welcome Admin]"
              >
<![CDATA[java.lang.AssertionError: Verify Welcome Message expected [Welcome Vishnu] but found [Welcome Admin]
  org.testng.Assert.fail(Assert.java:94)
  org.testng.Assert.failNotEquals(Assert.java:513)
  org.testng.Assert.assertEqualsImpl(Assert.java:135)
  org.testng.Assert.assertEquals(Assert.java:116)
  org.testng.Assert.assertEquals(Assert.java:190)
  com.orangehrm.tests.LoginTest.verifyLoginWithValidCredentials(LoginTest.java:18)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
  org.testng.TestRunner.privateRun(TestRunner.java:782)
  org.testng.TestRunner.run(TestRunner.java:632)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
  org.testng.SuiteRunner.run(SuiteRunner.java:268)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
  org.testng.TestNG.run(TestNG.java:1064)
  org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="verifyFooterMessage" time="0.135" classname="com.orangehrm.tests.LoginTest" />
                <testcase name="verifyLoginWithInvalidCredentials" time="2.011" classname="com.orangehrm.tests.LoginTest" />
                <testcase name="verifyLoginWithBlankUserName" time="0.440" classname="com.orangehrm.tests.LoginTest" />
                <testcase name="verifyLoginWithBlankPassword" time="0.409" classname="com.orangehrm.tests.LoginTest" />
      
</testsuite>
